### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [zhubikKar/-pu#1]
Если на сервере будет переназначена БД по умолчанию, то все скрипты будут выдавать ошибку. 
Задание 7 - рекомендуется OR использовать IN(....)
Задание 8 - не сделано
Задание 9 - нужно выбрать не все букинги (аренду), а пользователей. Их не так много. Выводить можно фамилию, имя, memid, например.
Задания 11 и далее - пока не сделаны

**Comment by zhubikKar** [comment]
Исправила ошибки и загрузила оставшиеся задания, загружала через VS Code с использованием git

**Comment by lasbio** [comment]
1. Каждая лабораторная должна быть в своей директории.
2. Задание 10 == отобрать 10, потом отсортировать. У вас отсортировать все, после отобрать 10. Результат, как понимаете, разный.
3. Задание 13 - Ваш скрипт вернет всех зарегистрированных, а по заданию нужно только последних.
4. Задние 14 - не правильно.

**Comment by zhubikKar** [comment]
Все задания исправила

**Comment by lasbio** [comment]
1. Если выполнено, то где директория с лаб 2?
2. Задание 10 - не верно.

**Comment by lasbio** [comment]
10 - не верно.  По заданию надо отобрать 10, потом отсортировать. 
SELECT ... FROM ... WHERE... ORDER BY.... LIMIT .... работает следующим образом:
сначала оптимизатор сервера выбирает индексы, по которым будет идти фильтрация (WHERE);
затем по этим индексам в память сервера будут извлечены все поля SELECT по критериям из WHERE;
затем будет проведена сортировка записей по критериям ORDER BY;
И только после клиенту из этих записей в памяти сервера будут возвращено то их количество, которое задано в LIMIT.
