### ISSUE TITLE
лаб 6

### ISSUE THREAD

**Issue by lasbio** [zhubikKar/-pu#4]
2,3 - что будет если в базе будут записи за несколько лет?
5 - вам надо вывести заглавными только те объекты, у которых есть в название слово теннис с заглавной буквы.
6 - не выполнена.

**Comment by zhubikKar** [comment]
В задании 2 будут в результате будут еще месяцы, то есть еще строчки
В задании 3 будут выведены еще месяцы и/или изменены процент использования объекта
В задании 5 не совсем понимаю, что у меня не так, условие, что выводятся только те объекты, у которых в названии есть "Tennis"
Задание 6 добавила

**Comment by lasbio** [comment]
по 2,3 я вам подсказку написал, а не попросил разъяснить.  Например, если у вас в базе будут данные за 2012-2023 год, то у вас скрипт в каждом месяце просуммирует за все года.  Кроме того, число аренд это sum(slots).
5 - должны быть отобраны только записи, у которых есть слово теннис с большой буквы.

**Comment by zhubikKar** [comment]
Все исправила
